#!/bin/bash

# Original author: github.com/cornercase
# Modified by: github.com/pauldenotter
# Written: August 8, 2020
# License: WTFPL

# Dependecies
# jq: in order to parse JSON
#   MacOS
#      ddcctl - for MacOS - https://github.com/kfix/ddcctl
#   Linux
#      ddccontrol - for linux - https://github.com/ddccontrol/ddccontrol

if command -v ddccontrol &> /dev/null
then
  OS='linux'
elif command -v ddcctl &> /dev/null
then
  OS='mac'
fi

MONITOR=$1
SOURCES='{"VGA-1": 1,"VGA-2": 2,"DVI-1": 3,"DVI-2": 4,"Composite video 1": 5,"Composite video 2": 6,"S-Video-1": 7,"S-Video-2": 8,"Tuner-1": 9,"Tuner-2": 10,"Tuner-3": 11,"Component video (YPrPb/YCrCb) 1": 12,"Component video (YPrPb/YCrCb) 2": 13,"Component video (YPrPb/YCrCb) 3": 14,"DisplayPort-1": 15,"DisplayPort-2": 16,"HDMI-1": 17,"HDMI-2": 18,"USB-C": 27}'
SOURCE=$(echo $SOURCES | jq '.["'${2}'"]')

case $OS in
  'mac' )
    ddcctl -d $MONITOR -i $SOURCE
    ;;
  'linux' )
    sudo ddccontrol -r 0x60 -w $SOURCE dev:$MONITOR
    ;;
esac
